enum BHFindingType{
    ASREPRoasting
    AzureNonT0ManagedIdentityAssignment
    AzureT0AddMembers
    AzureT0AddOwner
    AzureT0AddSecret
    AzureT0AKSContributor
    AzureT0AppAdmin
    AzureT0AutomationContributor
    AzureT0AvereContributor
    AzureT0CloudAppAdmin
    AzureT0Contributor
    AzureT0ExecuteCommand
    AzureT0GetCerts
    AzureT0GetKeys
    AzureT0GetSecrets
    AzureT0KeyVaultContributor
    AzureT0LogicAppContributor
    AzureT0MGAddMember
    AzureT0MGAddOwner
    AzureT0MGAddSecret
    AzureT0MGGrantAppRoles
    AzureT0MGGrantRole
    AzureT0Owner
    AzureT0Owns
    AzureT0ResetPassword
    AzureT0RoleActivationNoMFA
    AzureT0SyncedToEntraUser
    AzureT0UserAccessAdministrator
    AzureT0VMAdminLogin
    AzureT0VMContributor
    AzureT0WebsiteContributor
    Kerberoasting
    LargeDefaultGroupsAddAllowedToAct
    LargeDefaultGroupsAddKeyCredentialLink
    LargeDefaultGroupsAddMember
    LargeDefaultGroupsAddSelf
    LargeDefaultGroupsAdmins
    LargeDefaultGroupsAllExtendedRights
    LargeDefaultGroupsCoerceAndRelayNTLMToADCS
    LargeDefaultGroupsCoerceAndRelayNTLMToLDAP
    LargeDefaultGroupsCoerceAndRelayNTLMToLDAPS
    LargeDefaultGroupsCoerceAndRelayNTLMToSMB
    LargeDefaultGroupsDCOM
    LargeDefaultGroupsForceChangePassword
    LargeDefaultGroupsGenericAll
    LargeDefaultGroupsGenericWrite
    LargeDefaultGroupsManageCA
    LargeDefaultGroupsManageCertificates
    LargeDefaultGroupsOwns
    LargeDefaultGroupsOwnsLimitedRights
    LargeDefaultGroupsPSRemote
    LargeDefaultGroupsRDP
    LargeDefaultGroupsReadGMSA
    LargeDefaultGroupsReadLAPS
    LargeDefaultGroupsSQLAdmin
    LargeDefaultGroupsSyncLAPSPassword
    LargeDefaultGroupsWriteAccountRestrictions
    LargeDefaultGroupsWriteDacl
    LargeDefaultGroupsWriteGPLink
    LargeDefaultGroupsWriteOwner
    LargeDefaultGroupsWriteOwnerLimitedRights
    LargeDefaultGroupsWriteSPN
    NonT0DCSyncers
    T0ADCSESC1
    T0ADCSESC10a
    T0ADCSESC10b
    T0ADCSESC13
    T0ADCSESC3
    T0ADCSESC4
    T0ADCSESC6a
    T0ADCSESC6b
    T0ADCSESC9a
    T0ADCSESC9b
    T0AddAllowedToAct
    T0AddKeyCredentialLink
    T0AddMember
    T0AddSelf
    T0Admins
    T0AllExtendedRights
    T0AllowedToAct
    T0AllowedToDelegate
    T0CoerceAndRelayNTLMToADCS
    T0CoerceAndRelayNTLMToLDAP
    T0CoerceAndRelayNTLMToLDAPS
    T0CoerceAndRelayNTLMToSMB
    T0CoerceToTGT
    T0DCOM
    T0DumpSMSA
    T0ForceChangePassword
    T0GenericAll
    T0GenericWrite
    T0GoldenCert
    T0HasSIDHistory
    T0Logins
    T0ManageCA
    T0ManageCertificates
    T0MarkSensitive
    T0Owns
    T0OwnsLimitedRights
    T0PSRemote
    T0RDP
    T0ReadGMSA
    T0ReadLAPS
    T0SQLAdmin
    T0SyncedToADUser
    T0SyncLAPSPassword
    T0WriteAccountRestrictions
    T0WriteDACL
    T0WriteGPLink
    T0WriteOwner
    T0WriteOwnerLimitedRights
    T0WriteSPN
    }
